app:
  version: @project.version@
spark:
  #свойства с точкой нужно экранировать
  common-spark-props:
    "[spark.master]": local[*]
    "[spark.driver.host]": 127.0.0.1
    "[spark.executor.instances]": 1
    "[spark.executor.cores]": 1
    "[spark.executor.memory]": 2G
    "[spark.driver.memory]": SPARK_DRIVER_MEMORY
    "[spark.executor.memoryOverhead]": 3000
    "[spark.sql.shuffle.partitions]": 128
    "[mapreduce.fileoutputcommitter.marksuccessfuljobs]": "false"
kafka:
  common-consumer-props: &common-consumer-props
    "[bootstrap.servers]": localhost:9092
    "[enable.auto.commit]": false
    "[auto.offset.reset]": earliest
    "[max.poll.interval.ms]": 4200000
    "[request.timeout.ms]": 4205000
    "[session.timeout.ms]": 60000
    "[max.poll.records]": 1
    "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
    "[value.deserializer]": org.apache.kafka.common.serialization.StringDeserializer

  common-producer-props: &common-producer-props
    "[bootstrap.servers]": localhost:9092
    "[acks]": all
    #    "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
    "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer

  psa-task-consumer-props:
    group-id: KafkaInputHandlerEvent
    topic-name: task.channel
    partition-num: 1
    bootstrap-servers: localhost:9092
    props:
      <<: *common-consumer-props
      "[max.poll.records]": 1
  psa-task-result-producer-props:
    topic-name: test.kih.result.channel
    props:
      <<: *common-producer-props
server:
  port: 9095
  servlet:
    context-path: /api/v1/
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, status-messages, prometheus