{
 "title": "cp",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flowEnd_total{application=\"cp\"}",
     "legendFormat": "{{kafkaReceivedTopic}} - {{status}}"
    }
   ]
  },
  {
   "title": "Count total 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flowEnd_total{application=\"cp\"}[1h])",
     "legendFormat": "{{kafkaReceivedTopic}} - {{status}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Requests count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!~\".*actuator.*\", application=\"cp\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests count 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri!~\".*actuator.*\", application=\"cp\"}[1h])",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\", uri!~\".*actuator.*\", application=\"cp\"}[$__interval]) / rate(http_server_requests_seconds_count{exception=\"None\", uri!~\".*actuator.*\", application=\"bdcp\"}[$__interval])",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  }
 ]
}