{
 "title": "Psa Tasks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Task processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "psaTask_processing_seconds_count",
     "legendFormat": "Exception: {{exception}}"
    }
   ]
  },
  {
   "title": "Processing count 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(psaTask_processing_seconds_count[1h])",
     "legendFormat": "Exception: {{exception}}"
    }
   ]
  },
  { "title": "Result sending", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Result count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "psaTask_resultSending_seconds_count",
     "legendFormat": "Exception: {{exception}}"
    }
   ]
  },
  {
   "title": "Result Count 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(psaTask_resultSending_seconds_count[1h])",
     "legendFormat": "Exception: {{exception}}"
    }
   ]
  }
 ]
}